/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#3e5219',
        'primary-container': '#556b2f',
        'on-primary': '#ffffff',
        'on-primary-container': '#d0eba1',
        'primary-fixed': '#d2eca2',
        'on-primary-fixed': '#131f00',
        'on-primary-fixed-variant': '#394d14',
        'primary-fixed-dim': '#b6d088',
        secondary: '#566342',
        'secondary-container': '#d7e5bb',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5a6745',
        'secondary-fixed': '#dae8be',
        'on-secondary-fixed': '#141f05',
        'on-secondary-fixed-variant': '#3f4b2c',
        'secondary-fixed-dim': '#becca3',
        tertiary: '#6b4323',
        'tertiary-container': '#865a38',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffdac2',
        'tertiary-fixed': '#ffdcc5',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#653d1e',
        'tertiary-fixed-dim': '#f4bb92',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#fff8f4',
        surface: '#fff8f4',
        'surface-bright': '#fff8f4',
        'surface-dim': '#e8d7c5',
        'surface-container': '#fdebd8',
        'surface-container-low': '#fff1e4',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#f7e5d3',
        'surface-container-highest': '#f1e0cd',
        'surface-variant': '#f1e0cd',
        'surface-tint': '#50652a',
        outline: '#75796b',
        'outline-variant': '#c5c8b8',
        'on-background': '#231a0f',
        'on-surface': '#231a0f',
        'on-surface-variant': '#45483c',
        inverse: {
          surface: '#392f22',
          'on-surface': '#ffeedd',
          primary: '#b6d088',
        },
      },
      fontFamily: {
        display: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'soft-ambient': '0px 4px 20px rgba(85, 107, 47, 0.05)',
        'hover-lift': '0px 10px 25px rgba(85, 107, 47, 0.1)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.25rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1440px',
        unit: '8px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'bento-gap': '24px',
      },
    },
  },
  plugins: [],
}